apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
  name: publisher
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: publisher
  sessionAffinity: None
  type: ClusterIP
