apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: publisher
    version: v5-grpc-tracing
  name: publisher-v5-grpc-tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
      version: v5-grpc-tracing
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "True"
      labels:
        app: publisher
        version: v5-grpc-tracing
    spec:
      containers:
      - env:
        - name: GREETER_SERVICE
          value: greeter-grpc:9080
        image: core.apps.ocp.zyl.io/hello/publisher:v5-grpc-tracing
        imagePullPolicy: Always
        name: publisher
        ports:
        - containerPort: 9080
          name: web
          protocol: TCP
